// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1Sp_PB6EWtrhf9ykWiamxOmvBq9Etgw',
    appId: '1:22423194830:web:2cf17f2a320b660ffd549f',
    messagingSenderId: '22423194830',
    projectId: 'bdcoe-f1b45',
    authDomain: 'bdcoe-f1b45.firebaseapp.com',
    storageBucket: 'bdcoe-f1b45.firebasestorage.app',
    measurementId: 'G-WG5FS0L9NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0s1cX68Zbi-rHWpuBE4tH5lawQmxVYgc',
    appId: '1:22423194830:android:d9b725ce64a11ac0fd549f',
    messagingSenderId: '22423194830',
    projectId: 'bdcoe-f1b45',
    storageBucket: 'bdcoe-f1b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhQOrHEdnb7RnKzI6t5uuZmUwb6SiXZg',
    appId: '1:22423194830:ios:0413293e2e6928e3fd549f',
    messagingSenderId: '22423194830',
    projectId: 'bdcoe-f1b45',
    storageBucket: 'bdcoe-f1b45.firebasestorage.app',
    iosBundleId: 'com.example.bdcoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhQOrHEdnb7RnKzI6t5uuZmUwb6SiXZg',
    appId: '1:22423194830:ios:0413293e2e6928e3fd549f',
    messagingSenderId: '22423194830',
    projectId: 'bdcoe-f1b45',
    storageBucket: 'bdcoe-f1b45.firebasestorage.app',
    iosBundleId: 'com.example.bdcoe',
  );
}
